apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo_helpme:3200
    access: proxy
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: loki
        tags: [{ key: 'service.name', value: 'service' }]
        filterByTraceID: true
        filterBySpanID: false
      lokiSearch:
        datasourceUid: loki
      traceToMetrics:
        datasourceUid: prometheus