apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-redis-config
  namespace: helpme
  labels:
    app: auth-redis
    tier: cache
data:
  redis.conf: |
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    protected-mode yes
    loglevel warning
    save ""
    appendonly no
