apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-redis-pvc
  namespace: helpme
  labels:
    app: auth-redis
    tier: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
