apiVersion: v1
kind: Secret
metadata:
  name: auth-redis-secret
  namespace: helpme
  labels:
    app: auth-redis
    tier: cache
type: Opaque
stringData:
  REDIS_PASSWORD: auth_redis_secure_password_local
