apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pvc
  namespace: helpme
  labels:
    app: auth-postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
