apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-secret
  namespace: helpme
  labels:
    app: auth-postgres
    tier: database
type: Opaque
stringData:
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: auth_secure_password_local
  POSTGRES_DB: auth-database
