apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-service
  namespace: helpme
  labels:
    app: auth-postgres
    tier: database
spec:
  selector:
    app: auth-postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
